spring:
  datasource:
    username: user
    password: user
    url: jdbc:mysql://localhost:3306/my-games-shop?serverTimezone=UTC
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true

  data:
    rest:
     base-path: /api

